platform :ios, '10.0'

target 'SSKWebKit' do
    
use_frameworks!


 
    # UI
    pod 'SnapKit', '~> 5.0.0'

    pod 'MBProgressHUD'


    pod 'MJRefresh'


    pod 'IQKeyboardManagerSwift'


    # JSBridge
    pod 'WebViewJavascriptBridge', '~> 6.0'
    
    # JSON
    pod 'SwiftyJSON'


    
end
